// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koztqdimawyxjivsnxog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvenRxZGltYXd5eGppdnNueG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzUxOTMsImV4cCI6MjA2NTU1MTE5M30.ZOaaNOsS26CY-mk18VvyHLWP8_dhOxGws1m-I_2hLpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);